import { ReportData } from "../Types";

export function buildInfoCards(report: ReportData): string {

    return `

<div class="card">

<div class="info-grid">

<div class="info-card">

<div class="info-icon">

📅

</div>

<div>

<div class="info-title">

Generated On

</div>

<div class="info-value">

${report.generatedOn.toLocaleString()}

</div>

</div>

</div>

<div class="info-card">

<div class="info-icon">

👤

</div>

<div>

<div class="info-title">

Generated By

</div>

<div class="info-value">

${report.generatedBy}

</div>

</div>

</div>

<div class="info-card">

<div class="info-icon">

🏢

</div>

<div>

<div class="info-title">

Company

</div>

<div class="info-value">

${report.companyName}

</div>

</div>

</div>

</div>

</div>

`;
}