import { ReportData } from "../Types";

export function buildMetadata(report: ReportData): string {
    return `
    <section class="metadata">

        <div>
            <span class="label">Generated By</span>
            <span>${report.generatedBy}</span>
        </div>

        <div>
            <span class="label">Generated On</span>
            <span>${report.generatedOn.toLocaleString()}</span>
        </div>

    </section>
    `;
}